---

# https://docs.openshift.com/container-platform/3.5/install_config/persistent_storage/persistent_storage_nfs.html

- name: "Install NFS packages on RHEL"
  yum:
    name: "{{ pkg }}"
    state: present
  with_items: ["nfs-utils", "nfs-utils-lib"]
  loop_control:
    loop_var: pkg
  when: ansible_distribution == "Red Hat Enterprise Linux"

- name: "Install NFS packages on Centos"
  yum:
    name: nfs-utils
    state: present
  when: ansible_distribution == "CentOS"

- name: "Create an NFS share directory"
  file:
    path: "/home/share"
    state: directory

- name: "Open ports, 111 portmapper, 2049 nfs, 20048 mountd"
  iptables:
    action: insert
    chain: INPUT
    protocol: "{{ item[1] }}"
    destination_port: "{{ item[0] }}"
    jump: ACCEPT
  with_nested:
      - [111, 2049, 20048]
      - ["tcp", "udp"]

- name: "Ensure the NFS server is started"
  systemd:
    name: nfs-server
    state: started

- name: "Ensure the NFS server is enabled"
  systemd:
    name: nfs-server
    enabled: yes

- name: "Create share directory"
  file:
    path: "/home/share/{{ directory }}"
    owner: nfsnobody
    group: nfsnobody
    mode: 0700
    state: directory
  with_items: "{{ container_shares }}"
  loop_control:
    loop_var: directory

- name: "Configure directories to export"
  lineinfile:
    path: "/etc/exports"
    regexp: "^/home/share/{{ directory }}"
    line: "/home/share/{{ directory }} *(rw,async,all_squash)"
  with_items: "{{ container_shares }}"
  loop_control:
    loop_var: directory

- name: "Export nfs shares"
  command: /usr/sbin/exportfs -a
