---

- name: "Configure NFS servers"
  hosts: nfs
  roles:
  - "nfs_server"

- name: "Configure nodes for OCP install"
  hosts: nodes

  pre_tasks:

  - name: "Clear out old transactions"
    shell: "yum-complete-transaction --cleanup-only"

  - name: "Install base packages on cluster nodes"
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ required_packages }}"

  - name: "Ensure all packages are at their latest"
    yum:
      name: "*"
      state: latest

  roles:
  - {role: "nfs_client"}
  - {role: docker,
     storage: "production",
     block_device: "vdb"}
