---

- name: "Configure NFS servers"
  hosts: nfs
  tasks:
  - name: "Install and configure as an NFS server"
    import_role:
      name: "nfs_server"


- name: "Configure nodes for OCP install"
  hosts: all
  tasks:

  - name: "Clear out old transactions"
    shell: "yum-complete-transaction --cleanup-only"

  - name: "Install base packages on cluster nodes"
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ required_packages }}"

  - name: "Install NetworkManager"
    yum:
      name: "NetworkManager"
      state: present
    notify:
      - "Start NetworkManager"
    when: openshift_use_dnsmasq

  - name: "Ensure all packages are at their latest"
    yum:
      name: "*"
      state: latest

  handlers:
    - name: "Start NetworkManager"
      systemd:
        name: "NetworkManager"
        state: started
        enabled: yes

- name: "Configure nodes for OCP install"
  hosts: nodes
  tasks:

  - name: "Install and configure as an NFS client"
    import_role:
      name: "nfs_client"

  - name: "Install and configure Docker"
    import_role:
      name: "docker"
    vars:
     storage: "production"
     block_device: "vdb"

- import_playbook: "./configure/dnsmasq.yml"
