---

ocp_release: "release-3.6"

excluders:
- "atomic-openshift-excluder"
- "atomic-openshift-docker-excluder"

required_packages:
- "wget"
- "git"
- "net-tools"
- "bind-utils"
- "iptables-services"
- "bridge-utils"
- "bash-completion"
- "python-virtualenv"
