---

# Obviously I want to chance to location of this to somewhere more general
image_path: "/home/brian.duffy/libvirt/images"
subdomain: "ocp.cluster.local"

networks:
    - name: "openshift"
      mode: "nat"
      gateway: 10.10.10.1
      netmask: 255.255.255.0
      dhcp:
          range:
              start: 10.10.10.2
              end: 10.10.10.254

nodes:
    root_password: "{{ lookup('password', '~/.private/vm/password') }}"
    timezone: "Europe/Dublin"
    keymap:   "ie"
    ssh_key:  "/home/brian.duffy/.ssh/id_rsa.pub"
    base_image: "{{ image_path }}/rhel-server-7.4-x86_64-kvm.qcow2"
    os_variant: "rhel7"

    instances:

        - name: "nfs.{{ subdomain }}"
          host_groups: ["cluster", "nfs", "repo"]
          cpus: 2
          memory: 2048
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:00"
                ipv4: "10.10.10.10"
          disks:
              - path: "{{ image_path }}/nfs-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/ms01-disk2.qcow2"
                format: "qcow2"
                size: 20

        - name: "m01.{{ subdomain }}"
          host_groups: ["cluster", "masters", "nodes", "etcd"]
          cpus: 2
          memory: 2048
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:01"
                ipv4: "10.10.10.11"
          disks:
              - path: "{{ image_path }}/m01-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/m01-disk2.qcow2"
                format: "qcow2"
                size: 20

        - name: "n01.{{ subdomain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:02"
                ipv4: "10.10.10.12"
          disks:
              - path: "{{ image_path }}/n01-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/n01-disk2.qcow2"
                format: "qcow2"
                size: 20

        - name: "n02.{{ subdomain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:03"
                ipv4: "10.10.10.13"
          disks:
              - path: "{{ image_path }}/n02-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/n02-disk2.qcow2"
                format: "qcow2"
                size: 20

redhat:
    username: "{{ lookup('file', '~/.private/redhat/username')}}"
    password: "{{ lookup('password', '~/.private/redhat/password') }}"
    subscription:
        pool: "{{ lookup('file', '~/.private/redhat/ocp_subscription_pool_id') }}"
    repos:
        - "rhel-7-server-rpms"
        - "rhel-7-server-extras-rpms"
        - "rhel-7-fast-datapath-rpms"
        - "rhel-7-server-ose-3.5-rpms"
