---
# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.

# Go here for Ansible Inventory docs
# http://docs.ansible.com/ansible/latest/intro_inventory.html

# Go here to read about ansible.cfg config for the inventory
# https://github.com/openshift/openshift-ansible/tree/master/inventory

# Go here to read about how to configure indentation for Jinja2
# https://ansiblemaster.wordpress.com/2016/07/29/jinja2-lstrip_blocks-to-manage-indentation/

all:
    children:
        masters:
            hosts:
                master.ocp.cluster:
        cluster:
            hosts:
                dns.ocp.cluster:
                yum.ocp.cluster:
                nfs.ocp.cluster:
                master.ocp.cluster:
                node.ocp.cluster:
                registry.ocp.cluster:
        nfs:
            hosts:
                nfs.ocp.cluster:
        registry:
            hosts:
                registry.ocp.cluster:
        dns:
            hosts:
                dns.ocp.cluster:
        yum:
            hosts:
                yum.ocp.cluster:
        nodes:
            hosts:
                master.ocp.cluster:
                node.ocp.cluster:
