---

- name: "Clean '~/.ssh/known_hosts'"
  hosts: localhost
  connection: local
  become: yes
  gather_facts: false
  vars:
    user:  "{{ lookup('env', 'USER') }}"
    known: "/home/{{ user }}/.ssh/known_hosts"
  tasks:
  - name: "Remove hosts with domain name"
    lineinfile:
      path: "{{ known }}"
      state: absent
      regexp: "^\\w*.{{ domain }}"
