---

- name: "Provision Cluster Instances"
  become: no
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    LIBGUESTFS_BACKEND: "direct"
  vars:
    networks:  "{{ domain   | get_networks(cidr_blocks) }}"
    instances: "{{ hostvars | get_instances(domain, cidr_blocks) }}"
  roles:
  - role: "create_networks"
  - role: "create_instances"

- name: "Provision Cluster Instances"
  become: no
  hosts: localhost
  connection: local
  vars:
    configured_networks: "{{ domain | get_configured_networks }}"
    network_gateway: "{{ configured_networks.0.gateway }}"
  roles:
  - role: "dnsmasq"
    vars:
      host_device: "em1"
      nameservers:
      - server: "{{ domain }}"
        ipv4: "{{ network_gateway }}"
    become: yes
  tasks:
  - pause:
      seconds: 30

# TODO:
# Work Around; There is currently no xfs support for virt-resize
# so need to grow the root files system manually
- name: "Workaround virt-resize XFS bug"
  hosts: all
  gather_facts: false
  tasks:
  - name: "Make sure the root device is filling the disk"
    command: "xfs_growfs -d /dev/vda1"
