---

- name: "Tear Down Cluster"
  become: no
  hosts: localhost
  connection: local
  tasks:

  - set_fact:
      networks:  "{{ domain   | get_networks(cidr_blocks) }}"
      instances: "{{ hostvars | get_instances(domain, cidr_blocks) }}"

  - name: "list VMs"
    virt:
      command: list_vms
    register: output

  - name: "Get VM list"
    set_fact:
      vm_names: "{{ output.list_vms }}"

  - name: "Undefine/remove all VMs from KVM"
    virt:
      name: "{{ item.name }}"
      command: undefine
    when: item.name in vm_names
    with_items: "{{ instances }}"

  - name: "Find a list of VM disks for this cluster"
    command: >
      find {{ image_path }} -name "*.{{ domain }}.disk.*"
    register: output

  - name: "Gather facts about VM disks"
    set_fact:
      delete_disks: "{{ output.stdout_lines }}"

  - name: "Clean up all the disks"
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ delete_disks }}"

  - name: "List all cluster networks"
    virt_net:
      command: list_nets
    register: output

  - name: "Get cluster network list"
    set_fact:
      net_names: "{{ output.list_nets }}"

  - name: "Undefine/remove all networks from KVM"
    virt_net:
      state: absent
      name: "{{ item.name }}"
    when: item.name in net_names
    with_items: "{{ networks }}"
