---

- name: "Shutdown cluster"
  become: no
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - set_fact:
      networks:  "{{ domain | list_networks_in_domain }}"
      instances: "{{ domain | list_vms_in_domain }}"

  - name: "Shutdown all VMs"
    virt:
      name: "{{ item }}"
      state: shutdown
    with_items: "{{ instances }}"

  - name: "Render all networks inactive"
    virt_net:
      state: inactive
      name: "{{ item }}"
    with_items: "{{ networks }}"
