---

- name: "Start cluster"
  become: no
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - set_fact:
      networks:  "{{ domain | list_networks_in_domain }}"
      instances: "{{ domain | list_vms_in_domain }}"

  - name: "Check all networks exist and are active"
    virt_net:
      state: active
      name: "{{ item }}"
    with_items: "{{ networks }}"

  - name: "Check all VMs exist and are running"
    virt:
      name: "{{ item }}"
      state: running
    with_items: "{{ instances }}"
