---

- name: "Recreate libvirt networks with new configuration"
  become: no
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
      - name: "List all cluster networks"
        virt_net:
            command: list_nets
        register: output
      - name: "Get cluster network list"
        set_fact:
            net_names: "{{ output.list_nets }}"
      - name: "Undefine/remove all networks from KVM"
        virt_net:
            state: absent
            name: "{{ item.name }}"
        with_items: "{{ networks }}"
        when: item.name in net_names
  roles:
      - {role: create_networks}
  tasks:
      - name: "Assign instances static IPs for NICs via MAC address"
        command: |
          {% for nic in instance.nics %}
          {% if nic.ipv4 is defined %}
          virsh net-update {{ nic.network }} \
            add ip-dhcp-host '<host mac="{{ nic.mac }}" ip="{{ nic.ipv4 }}"/>' \
            --live --config
          {% endif %}
          {% endfor %}
        with_items: "{{ nodes.instances }}"
        loop_control:
            loop_var: "instance"
        become: yes
