---

domain: "ocp.cluster"

networks:
    - name: "ocp"
      mode: "nat"
      gateway: 10.10.10.1
      subnet: "10.10.10.0/24"
      netmask: 255.255.255.0
      dhcp:
          range:
              start: 10.10.10.2
              end: 10.10.10.254
      dns: 10.10.10.10

nodes:
    base_image: "{{ image_path }}/rhel-server-7.4-x86_64-kvm.qcow2"
    os_variant: "rhel7"
    instances:
        - name: "dns.{{ domain }}"
          host_groups: ["cluster", "dns"]
          cpus: 1
          memory: 512
          nics:
              - network: "ocp"
                model: "virtio"
                mac: "52:54:00:00:00:00"
                ipv4: "10.10.10.10"
          disks:
              - path: "{{ image_path }}/dns-disk1.qcow2"
                format: "qcow2"
        - name: "yum.{{ domain }}"
          host_groups: ["cluster", "yum"]
          cpus: 1
          memory: 512
          nics:
              - network: "ocp"
                model: "virtio"
                mac: "52:54:00:00:00:03"
                ipv4: "10.10.10.3"
          disks:
              - path: "{{ image_path }}/yum-disk1.qcow2"
                format: "qcow2"
                size: 100
        - name: "nfs.{{ domain }}"
          host_groups: ["cluster", "nfs"]
          cpus: 1
          memory: 512
          nics:
              - network: "ocp"
                model: "virtio"
                mac: "52:54:00:00:00:04"
                ipv4: "10.10.10.4"
          disks:
              - path: "{{ image_path }}nfs-disk1.qcow2"
                format: "qcow2"
                size: 60
        - name: "master.{{ domain }}"
          host_groups: ["cluster", "masters", "nodes"]
          cpus: 2
          memory: 2048
          nics:
              - network: "ocp"
                model: "virtio"
                mac: "52:54:00:00:00:05"
                ipv4: "10.10.10.5"
          disks:
              - path: "{{ image_path }}/master-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/master-disk2.qcow2"
                format: "qcow2"
                size: 20
        - name: "node.{{ domain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "ocp"
                model: "virtio"
                mac: "52:54:00:00:00:06"
                ipv4: "10.10.10.6"
          disks:
              - path: "{{ image_path }}/node-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/node-disk2.qcow2"
                format: "qcow2"
                size: 20
        - name: "registry.{{ domain }}"
          host_groups: ["cluster", "registry"]
          cpus: 2
          memory: 2048
          nics:
              - network: "ocp"
                model: "virtio"
                mac: "52:54:00:00:00:07"
                ipv4: "10.10.10.7"
          disks:
              - path: "{{ image_path }}/registry-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/registry-disk2.qcow2"
                format: "qcow2"
                size: 60

redhat:
    username: "{{ lookup('passwordstore', 'redhat/username')}}"
    password: "{{ lookup('passwordstore', 'redhat/password') }}"
    subscription:
        pool: "{{ lookup('passwordstore', 'redhat/ocp_subscription_pool_id') }}"
    rpms:
        repos:
        - "rhel-7-server-rpms"
        - "rhel-7-server-extras-rpms"
        - "rhel-7-fast-datapath-rpms"
        - "rhel-7-server-ose-3.5-rpms"
    ocp:
        tag: "v3.5.5.31.36"
        images:
        - "registry.access.redhat.com/openshift3/ose-f5-router"
        - "registry.access.redhat.com/openshift3/ose-deployer"
        - "registry.access.redhat.com/openshift3/ose"
        - "registry.access.redhat.com/openshift3/ose-egress-router"
        - "registry.access.redhat.com/openshift3/ose-keepalived-ipfailover"
        - "registry.access.redhat.com/openshift3/openvswitch"
        - "registry.access.redhat.com/openshift3/ose-recycler"
        - "registry.access.redhat.com/openshift3/ose-docker-builder"
        - "registry.access.redhat.com/openshift3/ose-docker-registry"
        - "registry.access.redhat.com/openshift3/ose-haproxy-router"
        - "registry.access.redhat.com/openshift3/node"
        - "registry.access.redhat.com/openshift3/ose-pod"
        - "registry.access.redhat.com/openshift3/ose-sti-builder"
    ocp_add:
        tag: "v3.5"
        images:
        - "registry.access.redhat.com/openshift3/logging-curator"
        - "registry.access.redhat.com/openshift3/logging-elasticsearch"
        - "registry.access.redhat.com/openshift3/logging-kibana"
        - "registry.access.redhat.com/openshift3/metrics-deployer"
        - "registry.access.redhat.com/openshift3/metrics-hawkular-openshift-agent"
        - "registry.access.redhat.com/openshift3/logging-auth-proxy"
        - "registry.access.redhat.com/openshift3/logging-deployer"
        - "registry.access.redhat.com/openshift3/logging-fluentd"
        - "registry.access.redhat.com/openshift3/metrics-cassandra"
        - "registry.access.redhat.com/openshift3/metrics-hawkular-metrics"
        - "registry.access.redhat.com/openshift3/metrics-heapster"
    ocp_extr:
        tag: "3.5"
        images:
        - "registry.access.redhat.com/openshift3/registry-console"
    ocp_s2i:
        images:
        - "registry.access.redhat.com/jboss-amq-6/amq63-openshift"
        - "registry.access.redhat.com/jboss-datagrid-7/datagrid71-openshift"
        - "registry.access.redhat.com/jboss-datagrid-7/datagrid71-client-openshift"
        - "registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift"
        - "registry.access.redhat.com/jboss-datavirt-6/datavirt63-driver-openshift"
        - "registry.access.redhat.com/jboss-decisionserver-6/decisionserver64-openshift"
        - "registry.access.redhat.com/jboss-processserver-6/processserver64-openshift"
        - "registry.access.redhat.com/jboss-eap-6/eap64-openshift"
        - "registry.access.redhat.com/jboss-eap-7/eap70-openshift"
        - "registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat7-openshift"
        - "registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat8-openshift"
        - "registry.access.redhat.com/openshift3/jenkins-1-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-2-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7"
        - "registry.access.redhat.com/rhscl/mongodb-32-rhel7"
        - "registry.access.redhat.com/rhscl/mysql-57-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7"
        - "registry.access.redhat.com/rhscl/perl-524-rhel7"
        - "registry.access.redhat.com/rhscl/php-56-rhel7"
        - "registry.access.redhat.com/rhscl/postgresql-95-rhel7"
        - "registry.access.redhat.com/rhscl/python-35-rhel7"
        - "registry.access.redhat.com/redhat-sso-7/sso70-openshift"
        - "registry.access.redhat.com/rhscl/ruby-24-rhel7"
        - "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"
        - "registry.access.redhat.com/redhat-sso-7/sso71-openshift"
        - "registry.access.redhat.com/rhscl/nodejs-4-rhel7"
        - "registry.access.redhat.com/rhscl/mariadb-101-rhel7"
