---

- name: "Create temporary directory '{{ create_instances_tmp_dir }}'"
  file:
    path: "{{ create_instances_tmp_dir }}"
    state: directory

- name: "Check instances from virsh"
  virt:
    command: list_vms
  register: output

- name: "Get a list of instances names"
  set_fact:
    instance_list: "{{ output.list_vms }}"

- include_tasks: provision_instance.yml
  when: instance.name not in instance_list
  with_items: "{{ nodes.instances }}"
  loop_control:
    loop_var: instance

- name: "Clean up temporary directory '{{ create_instances_tmp_dir }}'"
  file:
    path: "{{ create_instances_tmp_dir }}"
    state: absent
