---

- name: "Create temporary directory '{{ create_instances_tmp_dir }}'"
  file:
    path: "{{ create_instances_tmp_dir }}"
    state: directory

- name: "Get list of instances already provisioned"
  set_fact:
    instance_list: "{{ domain | list_vms_in_domain }}"

- include_tasks: provision_instance.yml
  when: instance.name not in instance_list
  with_items: "{{ instances }}"
  loop_control:
    loop_var: instance

- name: "Clean up temporary directory '{{ create_instances_tmp_dir }}'"
  file:
    path: "{{ create_instances_tmp_dir }}"
    state: absent
