---

image_path: "{{ lookup('passwordstore', 'vm/images') }}"
domain: "test.cluster.local"
networks:
    - name: "test.eth0"
      mode: "nat"
      gateway: 20.0.0.1
      netmask: 255.255.255.0
      dhcp:
          range:
              start: 20.0.0.2
              end: 20.0.0.254
nodes:
    root_password: "{{ lookup('passwordstore', 'vm/password') }}"
    timezone: "Europe/Dublin"
    keymap:   "ie"
    ssh_key:  "{{ lookup('passwordstore', 'vm/sshkey') }}"
    base_image: "{{ image_path }}/CentOS-7-x86_64-GenericCloud.qcow2"
    os_variant: "centos7.0"
    instances:
        - name: "node1.{{ domain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "test.eth0"
                model: "virtio"
                mac: "52:54:00:00:00:20"
                ipv4: "20.0.0.12"
          disks:
              - format: "qcow2"
        - name: "node2.{{ domain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "test.eth0"
                model: "virtio"
                mac: "52:54:00:00:00:21"
                ipv4: "20.0.0.13"
          disks:
              - format: "qcow2"
        - name: "node3.{{ domain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "test.eth0"
                model: "virtio"
                mac: "52:54:00:00:00:22"
                ipv4: "20.0.0.14"
          disks:
              - format: "qcow2"
