---
- name: "Ensure that there is a hosts file in the directory"
  file:
    path: "./hosts"
    state: touch
- name: "Generate groups for the hosts file"
  blockinfile:
    dest: "./hosts"
    marker: "# {mark} Generated Groups"
    block: |
       {% for name, hosts in node_groups.iteritems() %}
       [{{ name }}]
       {% for host in hosts %}
       {{ host }}.{{ subdomain }}
       {% endfor %}
       {% endfor %}
       {% for instance in nodes.instances %}
       [{{ instance.name }}]
       {{ instance.name }}.{{ subdomain }} ansible_host={{ instance.nics[0].ipv4 }}
       {% endfor %}
