---

- name: "Install an elasticsearch cluster"
  hosts: masters
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_port: 9201
  tasks:

  - name: "Install useful packages"
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ useful_packages }}"

  - name: "Install `{{ inventory_hostname }}` as a node"
    import_role:
      name: elasticsearch
    vars:
      es_version: "6.2.2"
      es_conf_dir: "/etc/elasticsearch"
      es_instance_name: "{{ inventory_hostname }}"
      es_data_dirs: "/opt/elasticsearch/data"
      es_log_dir:   "/opt/elasticsearch/logs"
      es_heap_size: "1g"
      es_api_port: 9200
      es_max_threads: 2048
      es_start_service: true
      es_java_install: true
      es_config:
        cluster.name: "{{ es_cluster_name }}"
        network.host: ['_eth0_', '_local_']
        discovery.zen.ping.unicast.hosts: "{{ groups.masters }}"
        discovery.zen.minimum_master_nodes: 2
        transport.tcp.port: 9300
        node.data: false
        node.master: true
        bootstrap.memory_lock: true
