---

- name: "Check networks from virsh"
  virt_net:
    command: list_nets
  register: output

- name: "Get a list of networks"
  set_fact:
    net_names: "{{ output.list_nets }}"

- name: "Define the networks"
  virt_net:
    command: define
    name: "{{ network.name }}"
    xml: '{{ lookup("template", "net-create.xml.j2") }}'
  with_items: "{{ networks }}"
  loop_control:
    loop_var: network
  when: network.name not in net_names

- name: "Start networks so it is activated"
  virt_net:
    name: "{{ item.name }}"
    state: active
  with_items: "{{ networks }}"

- name: "Set networks to autostart"
  virt_net:
    name: "{{ item.name }}"
    autostart: yes
  with_items: "{{ networks }}"
