---

# https://jamielinux.com/docs/libvirt-networking-handbook/index.html

- name: "Get list of networks already provisioned"
  set_fact:
    net_names: "{{ domain | list_networks_in_domain }}"

- name: "Define the networks"
  virt_net:
    command: define
    name: "{{ network.name }}"
    xml: '{{ lookup("template", "net-create.xml.j2") }}'
  when: network.name not in net_names
  with_items: "{{ networks }}"
  loop_control:
    loop_var: network

- name: "Get first network"
  set_fact:
    network: "{{ networks[0] }}"

- name: "Start networks so it is activated"
  virt_net:
    name: "{{ item.name }}"
    state: active
  with_items: "{{ networks }}"

- name: "Set networks to autostart"
  virt_net:
    name: "{{ item.name }}"
    autostart: yes
  with_items: "{{ networks }}"
