---
# Create an OSEv3 group that contains the master, nodes, etcd, and lb groups.
# The lb group lets Ansible configure HAProxy as the load balancing solution.
# Comment lb out if your load balancer is pre-configured.

# Go here for Ansible Inventory docs
# http://docs.ansible.com/ansible/latest/intro_inventory.html

# Go here to read about ansible.cfg config for the inventory
# https://github.com/openshift/openshift-ansible/tree/master/inventory

# Go here to read about how to configure indentation for Jinja2
# https://ansiblemaster.wordpress.com/2016/07/29/jinja2-lstrip_blocks-to-manage-indentation/

# Create an OSEv3 group that contains the masters and nodes groups
all:
    hosts:
        nfs.test.cluster.local
        m01.test.cluster.local
        n01.test.cluster.local
        n02.test.cluster.local
    children:
        masters:
            hosts:
                m01.test.cluster.local:
        repo:
            hosts:
                nfs.test.cluster.local:
        cluster:
            hosts:
                nfs.test.cluster.local:
                m01.test.cluster.local:
                n01.test.cluster.local:
                n02.test.cluster.local:
        nfs:
            hosts:
                nfs.test.cluster.local:
        etcd:
            hosts:
                m01.test.cluster.local:
        nodes:
            hosts:
                m01.test.cluster.local:
                n01.test.cluster.local:
                n02.test.cluster.local:
