---

# Base Cluster:
# - Review `./group_vars/all/vars.yml`
# - A set of procedurally described VMs
# - A procedurally described host network
# - Activate local DNS to resolve host and guest FQDN via NetworkManager

- import_playbook: ../../playbooks/provision.yml
  tags: ["provision"]

- import_playbook: ../../playbooks/startup.yml
  tags: ["startup"]

- import_playbook: ../../playbooks/clean_hosts.yml
  tags: ["clean-hosts", "teardown"]

- import_playbook: ../../playbooks/shutdown.yml
  tags: ["shutdown", "teardown"]

- import_playbook: ../../playbooks/teardown.yml
  tags: ["teardown"]
