---

- name: "Setup hosts for a disconnected repo"
  hosts: repo
  roles:
      - {role: subscribe,
          username: "{{ redhat.username }}",
          password: "{{ redhat.password }}",
          pools: ["{{ redhat.subscription.pool }}"],
          repos: "{{ redhat.repos }}"}
      - {role: docker, storage: "production", block_device: "vdb"}
  tasks:
      - name: "Install packages to make this node our repo"
        yum:
            name: "{{ item }}"
            state: present
        with_items: ["yum-utils", "createrepo", "git", "httpd"]
