---

- name: "Provision cluster"
  become: no
  hosts: localhost
  connection: local
  pre_tasks:
    environment:
      LIBGUESTFS_BACKEND: direct
  roles:
    - {role: create_networks}
    - {role: create_instances}
    - {role: generate_hostfile}
