---

- name: "Shutdown cluster"
  become: no
  hosts: localhost
  connection: local
  tasks:
    - name: "Shutdown all VMs"
      virt:
        name: "{{ vm.name }}"
        state: shutdown
      with_items: "{{ nodes.instances }}"
      loop_control:
        loop_var: vm
    - name: "render all networks inactive"
      virt_net:
        state: inactive
        name: "{{ network.name }}"
      with_items: "{{ networks }}"
      loop_control:
        loop_var: network
