---

- name: "Recreate libvirt networks with new configuration"
  become: no
  hosts: localhost
  connection: local
  pre_tasks:
      - name: "List all cluster networks"
        virt_net:
            command: list_nets
        register: output
      - name: "Get cluster network list"
        set_fact:
            net_names: "{{ output.list_nets }}"
      - name: "Undefine/remove all networks from KVM"
        virt_net:
            state: absent
            name: "{{ item.name }}"
        with_items: "{{ networks }}"
        when: item.name in net_names
  roles:
      - {role: create_networks}
