---

- name: "Install dnsmaq"
  yum:
      name: "dnsmasq"
      state: present

- name: "Disable NetworkManager"
  systemd:
      name: "NetworkManager"
      state: stopped
      enabled: no

- name: "Remove NetworkManager"
  yum:
      name: "NetworkManager"
      state: absent

- name: "Disable PEERDNS"
  lineinfile:
    path: "/etc/sysconfi/network-scripts/ifcfg-eth0"
    regexp: '^PEERDNS='
    line: 'PEERDNS="no"'
    state: present

- name: "Thoroughly turn off NetworkManager Control"
  lineinfile:
    path: "/etc/sysconfi/network-scripts/ifcfg-eth0"
    regexp: '^NM_CONTROLLED='
    line: 'NM_CONTROLLED="no"'
    state: present

- name: "Copy /etc/dnsmasq.conf"
  template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"

- name: "Copy /etc/hosts"
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"

- name: "Copy /etc/resolv.conf"
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"

- name: "Enable and start dnsmasq"
  systemd:
      name: "dnsmasq"
      state: start
      enabled: yes

- name: "Enable and start dnsmasq"
  systemd:
      name: "network"
      state: restart
