---

- name: "Install dnsmaq"
  yum:
      name: "dnsmasq"
      state: present

- name: "Remove NetworkManager"
  yum:
      name: "NetworkManager"
      state: absent

- name: "Disable PEERDNS"
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-eth0"
    regexp: '^PEERDNS='
    line: 'PEERDNS="no"'
    state: present

- name: "Thoroughly turn off NetworkManager Control"
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-eth0"
    regexp: '^NM_CONTROLLED='
    line: 'NM_CONTROLLED="no"'
    state: present

- name: "Copy /etc/dnsmasq.conf"
  template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"

- name: "Copy /etc/hosts"
  template:
    src: "hosts.j2"
    dest: "/etc/dnsmasq_static_hosts.conf"

- name: "Enable and start dnsmasq"
  systemd:
      name: "dnsmasq"
      state: started
      enabled: yes

- name: "Restart network"
  systemd:
      name: "network"
      state: restarted
