---

# Base Cluster Provision:
# - Review `./group_vars/all/vars.yml`
# - A set of procedurally described VMs
# - A procedurally described host network
# - Activate local DNS to resolve host and guest FQDN via NetworkManager

- import_playbook: ../../playbooks/provision.yml
  tags: ["provision"]

- import_playbook: ../../playbooks/hostfile.yml
  tags: ["provision", "hostfile"]

# TODO:
# Work Around; There is currently no xfs support for virt-resize
# so need to grow the root files system manually
- name: "Workaround virt-resize XFS bug"
  hosts: all
  tags: ["provision"]
  tasks:
      - name: "Make sure the root device is filling the disk"
        command: "xfs_growfs -d /dev/vda1"

- import_playbook: ../../playbooks/startup.yml
  tags: ["startup"]

- import_playbook: ../../playbooks/yum_repo.yml
  tags: ["provision", "ocp", "yum"]

- import_playbook: ../../playbooks/dns.yml
  tags: ["provision", "ocp", "dns"]

- import_playbook: ../../playbooks/nfs.yml
  tags: ["provision", "ocp", "nfs"]

- import_playbook: ../../playbooks/ocp_prep.yml
  tags: ["provision", "ocp", "prep"]

# Base Cluster TearDown:

- import_playbook: ../../playbooks/unsubscribe.yml
  tags: ["teardown"]

- import_playbook: ../../playbooks/clean_hosts.yml
  tags: ["clean-hosts", "teardown"]

- import_playbook: ../../playbooks/shutdown.yml
  tags: ["shutdown", "teardown"]

- import_playbook: ../../playbooks/teardown.yml
  tags: ["teardown"]

# Update network

- import_playbook: ../../playbooks/update_networks.yml
  tags: ["update-networks"]
