---

- name: "Install docker service"
  yum:
    name: "docker"
    state: present

- name: "Set docker options"
  lineinfile:
    dest: "/etc/sysconfig/docker"
    line: "OPTIONS='--selinux-enabled --insecure-registry 172.30.0.0/16'"
    regexp: "^OPTIONS="
    state: present

# configure docker storage
- import_tasks: docker_storage_setup.yml
  when: storage == "production"
  notify: start docker
