---

# TODO: This should be a less specific location
image_path: "/home/brian.duffy/libvirt/images"

subdomain: "ocp.cluster.local"

networks:
    - name: "openshift"
      mode: "nat"
      gateway: 10.10.10.1
      netmask: 255.255.255.0
      dhcp:
          range:
              start: 10.10.10.2
              end: 10.10.10.254

nodes:
    root_password: "{{ lookup('password', '~/.private/vm/password') }}"
    timezone: "Europe/Dublin"
    keymap:   "ie"
    ssh_key:  "/home/brian.duffy/.ssh/id_rsa.pub"
    base_image: "{{ image_path }}/rhel-server-7.4-x86_64-kvm.qcow2"
    os_variant: "rhel7"

    instances:

        - name: "nfs.{{ subdomain }}"
          host_groups: ["cluster", "nfs", "repo"]
          cpus: 2
          memory: 2048
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:00"
                ipv4: "10.10.10.10"
          disks:
              - path: "{{ image_path }}/nfs-disk1.qcow2"
                format: "qcow2"
                size: 100
              - path: "{{ image_path }}/nfs-disk2.qcow2"
                format: "qcow2"
                size: 50

        - name: "m01.{{ subdomain }}"
          host_groups: ["cluster", "masters", "nodes", "etcd"]
          cpus: 2
          memory: 2048
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:01"
                ipv4: "10.10.10.11"
          disks:
              - path: "{{ image_path }}/m01-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/m01-disk2.qcow2"
                format: "qcow2"
                size: 20

        - name: "n01.{{ subdomain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:02"
                ipv4: "10.10.10.12"
          disks:
              - path: "{{ image_path }}/n01-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/n01-disk2.qcow2"
                format: "qcow2"
                size: 20

        - name: "n02.{{ subdomain }}"
          host_groups: ["cluster", "nodes"]
          cpus: 1
          memory: 1024
          nics:
              - network: "openshift"
                model: "virtio"
                mac: "52:54:00:00:00:03"
                ipv4: "10.10.10.13"
          disks:
              - path: "{{ image_path }}/n02-disk1.qcow2"
                format: "qcow2"
              - path: "{{ image_path }}/n02-disk2.qcow2"
                format: "qcow2"
                size: 20

redhat:
    username: "{{ lookup('file', '~/.private/redhat/username')}}"
    password: "{{ lookup('password', '~/.private/redhat/password') }}"
    subscription:
        pool: "{{ lookup('file', '~/.private/redhat/ocp_subscription_pool_id') }}"
    rpms:
        repos:
        - "rhel-7-server-rpms"
        - "rhel-7-server-extras-rpms"
        - "rhel-7-fast-datapath-rpms"
        - "rhel-7-server-ose-3.5-rpms"
    ocp:
        tag: "v3.5.5.31.36"
        images:
        - "registry.access.redhat.com/openshift3/ose-f5-router"
        - "registry.access.redhat.com/openshift3/ose-deployer"
        - "registry.access.redhat.com/openshift3/ose"
        - "registry.access.redhat.com/openshift3/ose-egress-router"
        - "registry.access.redhat.com/openshift3/ose-keepalived-ipfailover"
        - "registry.access.redhat.com/openshift3/openvswitch"
        - "registry.access.redhat.com/openshift3/ose-recycler"
        - "registry.access.redhat.com/openshift3/ose-docker-builder"
        - "registry.access.redhat.com/openshift3/ose-docker-registry"
        - "registry.access.redhat.com/openshift3/ose-haproxy-router"
        - "registry.access.redhat.com/openshift3/node"
        - "registry.access.redhat.com/openshift3/ose-pod"
        - "registry.access.redhat.com/openshift3/ose-sti-builder"
    ocp_add:
        tag: "v3.5"
        images:
        - "registry.access.redhat.com/openshift3/logging-curator"
        - "registry.access.redhat.com/openshift3/logging-elasticsearch"
        - "registry.access.redhat.com/openshift3/logging-kibana"
        - "registry.access.redhat.com/openshift3/metrics-deployer"
        - "registry.access.redhat.com/openshift3/metrics-hawkular-openshift-agent"
        - "registry.access.redhat.com/openshift3/logging-auth-proxy"
        - "registry.access.redhat.com/openshift3/logging-deployer"
        - "registry.access.redhat.com/openshift3/logging-fluentd"
        - "registry.access.redhat.com/openshift3/metrics-cassandra"
        - "registry.access.redhat.com/openshift3/metrics-hawkular-metrics"
        - "registry.access.redhat.com/openshift3/metrics-heapster"
    ocp_extr:
        tag: "3.5"
        images:
        - "registry.access.redhat.com/openshift3/registry-console"
    ocp_s2i:
        images:
        - "registry.access.redhat.com/jboss-amq-6/amq63-openshift"
        - "registry.access.redhat.com/jboss-datagrid-7/datagrid71-openshift"
        - "registry.access.redhat.com/jboss-datagrid-7/datagrid71-client-openshift"
        - "registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift"
        - "registry.access.redhat.com/jboss-datavirt-6/datavirt63-driver-openshift"
        - "registry.access.redhat.com/jboss-decisionserver-6/decisionserver64-openshift"
        - "registry.access.redhat.com/jboss-processserver-6/processserver64-openshift"
        - "registry.access.redhat.com/jboss-eap-6/eap64-openshift"
        - "registry.access.redhat.com/jboss-eap-7/eap70-openshift"
        - "registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat7-openshift"
        - "registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat8-openshift"
        - "registry.access.redhat.com/openshift3/jenkins-1-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-2-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7"
        - "registry.access.redhat.com/rhscl/mongodb-32-rhel7"
        - "registry.access.redhat.com/rhscl/mysql-57-rhel7"
        - "registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7"
        - "registry.access.redhat.com/rhscl/perl-524-rhel7"
        - "registry.access.redhat.com/rhscl/php-56-rhel7"
        - "registry.access.redhat.com/rhscl/postgresql-95-rhel7"
        - "registry.access.redhat.com/rhscl/python-35-rhel7"
        - "registry.access.redhat.com/redhat-sso-7/sso70-openshift"
        - "registry.access.redhat.com/rhscl/ruby-24-rhel7"
        - "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"
        - "registry.access.redhat.com/redhat-sso-7/sso71-openshift"
        - "registry.access.redhat.com/rhscl/nodejs-4-rhel7"
        - "registry.access.redhat.com/rhscl/mariadb-101-rhel7"
