# https://access.redhat.com/containers
# https://github.com/openshift/openshift-ansible/tree/master/inventory

ansible_ssh_user: root

# 0 to log errors and warnings only
# 2 to log normal information (This is the default level.)
# 4 to log debugging-level information
# 6 to log API-level debugging information (request / response)
# 8 to log body-level API debugging information
debug_level: 8
openshift_deployment_type: origin

# Versions
openshift_release               : "v3.7"
openshift_upgrade_target        : "v3.7"
openshift_image_tag             : "v3.7.2"
openshift_pkg_version           : "-3.7.1"
#openshift_metrics_image_version : "v3.7"
#openshift_logging_image_version : "v3.7"

containerized: true
system_images_registry: "registry.access.redhat.com"

osm_etcd_image: "registry.access.redhat.com/rhel7/etcd"
osm_use_cockpit: false
openshift_cockpit_deployer_prefix: "registry.access.redhat.com/openshift3/"

# skip these checks for local libvirt deploy, they won't pass because you can't
# allocate the recommended system resources
openshift_disable_check:
- memory_availability
- disk_availability
- docker_image_availability

# This variable overrides the node selector that projects will
# use by default when placing pods.
osm_default_node_selector: "region=infra"

# SDN cluster network CIDR block from which pod IPs are assigned
# Must not conflict with existing network blocks in your infrastructure.
# Defaults 10.128.0.0/14 cannot be arbitrarily re-configured after deployment
osm_cluster_network_cidr: "10.128.0.0/14"
openshift_use_openshift_sdn: true
os_sdn_network_plugin_name: "redhat/openshift-ovs-subnet"
openshift_use_dnsmasq: true
openshift_ca_host: "master1.test.origin.local"

openshift_router_selector:   'region=infra'
openshift_registry_selector: 'region=infra'

# master api console and ports
#openshift_master_api_port=443
#openshift_master_console_port=8756

# enable ntp on masters to ensure proper failover, probably needed for HA only?
openshift_clock_enabled: true

# add this file and some dummy users in post configuration step
openshift_master_identity_providers:
- name: "htpasswd_auth"
  login: true
  challenge: true
  kind: "HTPasswdPasswordIdentityProvider"
  filename: "/etc/origin/master/htpasswd"

openshift_master_default_subdomain: "{{ wildcard_subdomain }}"

# host variables applied to all nodes
openshift_docker_options: "--log-driver json-file --log-opt max-size=1M --log-opt max-file=3"
openshift_node_kubelet_args:
  pods-per-core: ['10']
  max-pods: ['20']
  image-gc-high-threshold: ['10']
  image-gc-low-threshold: ['5']

oreg_url: "registry.access.redhat.com/openshift3/ose-${component}:${version}"
openshift_examples_modify_imagestreams: true
openshift_docker_additional_registries:
- "registry.access.redhat.com"
- "hub.docker.com"
- "docker.io"
openshift_docker_insecure_registries:
- "registry.access.redhat.com"
- "hub.docker.com"
- "docker.io"
- "172.30.0.0/16"
openshift_docker_blocked_registries: []

openshift_hosted_manage_registry: true
openshift_hosted_registry_selector: "region=infra"
openshift_hosted_registry_replicas: 1
openshift_hosted_registry_cert_expire_days: 730
openshift_hosted_registry_storage_kind: "nfs"
openshift_hosted_registry_storage_access_modes: ['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory: "/exports"
openshift_hosted_registry_storage_nfs_options: "*(rw,root_squash)"
openshift_hosted_registry_storage_volume_name: "registry"
openshift_hosted_registry_storage_volume_size: "10Gi"

openshift_enable_service_catalog: false

# Turn off logging and metrics for now
openshift_metrics_install_metrics : false
openshift_logging_install_logging : false
