---

- name: "Install NFS packages"
  yum:
    name: "nfs-utils"

- name:  "Start NFS clients"
  systemd:
    name: nfs
    state: started

- name: "Enable services"
  systemd:
    name: nfs
    enabled: yes

- name: "Default all container access for NFS"
  seboolean:
    name: "{{ selopt }}"
    state: yes
    persistent: yes
  with_items: ["virt_use_nfs", "virt_sandbox_use_nfs"]
  loop_control:
    loop_var: selopt
