---

- name: "Provision Cluster"
  become: no
  hosts: localhost
  connection: local
  environment:
    LIBGUESTFS_BACKEND: "direct"
  tasks:
  - set_fact:
      networks:  "{{ domain   | get_networks(cidr_blocks) }}"
      instances: "{{ hostvars | get_instances(domain, cidr_blocks) }}"
  - import_role:
      name: "create_networks"
  - import_role:
      name: "create_instances"
  - pause:
      seconds: 30

# TODO:
# Work Around; There is currently no xfs support for virt-resize
# so need to grow the root files system manually
- name: "Workaround virt-resize XFS bug"
  hosts: all
  tasks:
  - name: "Make sure the root device is filling the disk"
    command: "xfs_growfs -d /dev/vda1"
