---

# Base Cluster Provision:
# - Review `./group_vars/all/vars.yml`
# - A set of procedurally described VMs
# - A procedurally described host network
# - Activate local DNS to resolve host and guest FQDN via NetworkManager

- include: ../../plays/provision.yml
  tags: ["provision"]

- include: ../../plays/startup.yml
  tags: ["startup"]

# Openshift Container Platform (Enterprise) System Preparation

- include: ../../plays/openshift_hostfile.yml
  tags: ["hostfile"]

- name: "Subscribe repo node to Red Hat CDN network"
  hosts: repo
  tags: ["provision", "openshift"]
  roles:
      - {role: subscribe,
          username: "{{ redhat.username }}",
          password: "{{ redhat.password }}",
          pools: ["{{ redhat.subscription.pool }}"],
          repos: "{{ redhat.rpms.repos }}"}

- include: ../../plays/openshift_disconnected.yml
  tags: ["provision", "openshift"]

- include: ../../plays/openshift_nfs_shares.yml
  tags: ["provision", "openshift"]

- name: "Unsubscribe repo node from Red Hat CDN network"
  hosts: repo
  tags: ["teardown"]
  tasks:
    - command: "subscription-manager remove --all"
    - command: "subscription-manager unregister"

# Base Cluster TearDown:

- include: ../../plays/shutdown.yml
  tags: ["shutdown", "teardown"]

- include: ../../plays/teardown.yml
  tags: ["teardown"]
