---

# Base Cluster Provision:
# - Review `./group_vars/all/vars.yml`
# - A set of procedurally described VMs
# - A procedurally described host network
# - Activate local DNS to resolve host and guest FQDN via NetworkManager

- include: ../../plays/provision.yml
  tags: ["provision"]

- include: ../../plays/startup.yml
  tags: ["startup"]

# Openshift Container Platform (Enterprise) System Preparation

- include: ../../plays/openshift_hostfile.yml
  tags: ["hostfile"]

- name: "Subscribe repo node to Red Hat CDN network"
  hosts: repo
  roles:
      - {role: subscribe,
          username: "{{ redhat.username }}",
          password: "{{ redhat.password }}",
          pools: ["{{ redhat.subscription.pool }}"],
          repos: "{{ redhat.rpms.repos }}"}
  tags: ["provision", "openshift"]

- include: ../../plays/openshift_disconnected.yml
  tags: ["provision", "openshift"]

- name: "Configure NFS servers"
  hosts: nfs
  roles:
      - {role: nfs_server,
               container_shares: ["registry", "logging", "metrics"]}
  tags: ["provision", "openshift"]

- name: "Configure NFS clients"
  hosts: nodes
  roles:
      - {role: nfs_client}
  tags: ["provision", "openshift"]

# Add this in later
# - include: ../../plays/openshift_host_prep.yml
#   tags: ["provision", "openshift"]

- name: "Unsubscribe repo node from Red Hat CDN network"
  hosts: repo
  tags: ["teardown"]
  tasks:
    - name: "Removing all subscriptions"
      command: "subscription-manager remove --all"
    - name: "Unregistering all systems"
      command: "subscription-manager unregister"

# Base Cluster TearDown:

- include: ../../plays/shutdown.yml
  tags: ["shutdown", "teardown"]

- include: ../../plays/teardown.yml
  tags: ["teardown"]
