---

- name: "Check if '{{ inventory_hostname }}' is registered"
  command: "subscription-manager status"
  register: output

- name: "Get the systems current status"
  set_fact:
      status: "{{ output.stdout_lines[3].split()[2] }}"

- debug:
      msg: "'{{ inventory_hostname }}' current status: '{{ status }}'"

- include: register_and_subscribe.yml
  when: status != "Current"
